name: Godsvagn upload
description: Upload a debfile to godsvagn

inputs:
  file:
    description: Files to upload
    required: false
  upload_url: # required if file is specified
    description: Where to upload said files
  regenerate_url:
    description: Regenerate url to call

runs:
  using: node20
  main: dist/index.js
